In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dataset = pd.read_csv('dseats_2024_training_dataset.csv')

val_data = pd.read_csv('dseats_2024_validation_dataset.csv')
dataset

,PRODUCTION DATE,Field Name,WELL_BORE_CODE,N_WELL_BORE_CODE,WellBore Name,FLOW_KIND,WELL_TYPE,Downhole Pressure (PSI),Downhole Temperature (Kelvin),Average Tubing Pressure,Annulus Pressure (PSI),AVG WHP (PSI),Choke Size,Oil Production (stb/day),Gas Volume (scf/day),Water Production (stb/day)
0,07/04/2014 00:00,DSEAT,DSEAT-001-F-1 C,105,001-F-1 C,production,OP,0.000000,273.150000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000,0.0000
1,08/04/2014 00:00,DSEAT,DSEAT-001-F-1 C,105,001-F-1 C,production,OP,0.000000,273.150000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000,0.0000
2,09/04/2014 00:00,DSEAT,DSEAT-001-F-1 C,105,001-F-1 C,production,OP,0.000000,273.150000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000,0.0000
3,10/04/2014 00:00,DSEAT,DSEAT-001-F-1 C,105,001-F-1 C,production,OP,0.000000,273.150000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000,0.0000
4,11/04/2014 00:00,DSEAT,DSEAT-001-F-1 C,105,001-F-1 C,production,OP,4500.454030,370.025890,4020.534770,0.000000,479.919260,33.071950,0.0000,0.000,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6920,26/06/2015 00:00,DSEAT,DSEAT-001-F-15 D,109,001-F-15 D,production,OP,2903.229117,379.373252,2460.629972,182.554483,442.599145,1.880480,747.8181,614123.984,64.2838
6921,27/06/2015 00:00,DSEAT,DSEAT-001-F-15 D,109,001-F-15 D,production,OP,2905.030564,379.379814,2456.159205,184.106427,448.871358,2.120109,749.2019,614168.462,64.4725
6922,28/06/2015 00:00,DSEAT,DSEAT-001-F-15 D,109,001-F-15 D,production,OP,2928.389988,379.313739,2484.425946,175.609150,443.964042,1.980460,789.9611,648175.070,65.9192
6923,29/06/2015 00:00,DSEAT,DSEAT-001-F-15 D,109,001-F-15 D,production,OP,2939.874982,379.288114,2496.000496,173.255362,443.874486,1.692930,789.7724,637067.219,63.3403
6924,30/06/2015 00:00,DSEAT,DSEAT-001-F-15 D,109,001-F-15 D,production,OP,2915.465730,379.366109,2469.645737,182.891962,445.819994,2.080569,802.9814,642509.067,61.8936

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6925 entries, 0 to 6924
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   PRODUCTION DATE                6925 non-null   object
 1   Field Name                     6925 non-null   object
 2   WELL_BORE_CODE                 6925 non-null   object
 3   N_WELL_BORE_CODE               6925 non-null   int64
 4   WellBore Name                  6925 non-null   object
 5   FLOW_KIND                      6925 non-null   object
 6   WELL_TYPE                      6925 non-null   object
 7   Downhole Pressure (PSI)        6925 non-null   float64
 8   Downhole Temperature (Kelvin)  6925 non-null   float64
 9   Average Tubing Pressure        6925 non-null   float64
 10  Annulus Pressure (PSI)         6925 non-null   float64
 11  AVG WHP (PSI)                  6925 non-null   float64
 12  Choke Size                     6919 non-null   float64
 13  Oil Production (stb/day)       6925 non-null   float64
 14  Gas Volume (scf/day)           6925 non-null   float64
 15  Water Production (stb/day)     6925 non-null   float64
dtypes: float64(9), int64(1), object(6)
memory usage: 865.8+ KB

In [4]:
val_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9920 entries, 0 to 9919
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   PRODUCTION DATE                2075 non-null   object
 1   Field Name                     2075 non-null   object
 2   WELL_BORE_CODE                 2075 non-null   object
 3   N_WELL_BORE_CODE               2075 non-null   float64
 4   WellBore Name                  2075 non-null   object
 5   FLOW_KIND                      2075 non-null   object
 6   WELL_TYPE                      2075 non-null   object
 7   Downhole Pressure (PSI)        2075 non-null   float64
 8   Downhole Temperature (Kelvin)  2075 non-null   float64
 9   Average Tubing Pressure        2075 non-null   float64
 10  Annulus Pressure (PSI)         2075 non-null   float64
 11  AVG WHP (PSI)                  2075 non-null   float64
 12  Choke Size                     2075 non-null   float64
 13  Oil Production (stb/day)       0 non-null      float64
 14  Gas Volume (scf/day)           0 non-null      float64
 15  Water Production (stb/day)     0 non-null      float64
dtypes: float64(10), object(6)
memory usage: 1.2+ MB

In [5]:
dataset.isna().sum()

PRODUCTION DATE                  0
Field Name                       0
WELL_BORE_CODE                   0
N_WELL_BORE_CODE                 0
WellBore Name                    0
FLOW_KIND                        0
WELL_TYPE                        0
Downhole Pressure (PSI)          0
Downhole Temperature (Kelvin)    0
Average Tubing Pressure          0
Annulus Pressure (PSI)           0
AVG WHP (PSI)                    0
Choke Size                       6
Oil Production (stb/day)         0
Gas Volume (scf/day)             0
Water Production (stb/day)       0
dtype: int64

In [6]:
val_data.shape

(9920, 16)

In [7]:
# Drop rows from index 10 to 20 (inclusive)
val_data = val_data.drop(val_data.index[2075:9921])

In [8]:
dataset.describe().T

,count,mean,std,min,25%,50%,75%,max
N_WELL_BORE_CODE,6925.0,1.072970e+02,9.801606e-01,105.0000,1.070000e+02,1.070000e+02,1.080000e+02,1.090000e+02
Downhole Pressure (PSI),6925.0,2.587483e+03,1.588474e+03,0.0000,0.000000e+00,3.378397e+03,3.664905e+03,4.606667e+03
Downhole Temperature (Kelvin),6925.0,3.496748e+02,4.624082e+01,273.1500,2.731500e+02,3.769114e+02,3.794962e+02,3.816522e+02
Average Tubing Pressure,6925.0,2.161986e+03,1.053875e+03,0.0000,8.966123e+02,2.472032e+03,2.907047e+03,4.592613e+03
Annulus Pressure (PSI),6925.0,1.803694e+02,1.397715e+02,0.0000,0.000000e+00,2.130911e+02,3.003568e+02,4.352875e+02
AVG WHP (PSI),6925.0,7.165769e+02,3.478600e+02,0.0000,4.765398e+02,6.196478e+02,9.038905e+02,1.991010e+03
Choke Size,6919.0,2.186456e+01,2.230069e+01,0.0000,4.631982e+00,1.430166e+01,3.152977e+01,1.257186e+02
Oil Production (stb/day),6925.0,8.494775e+03,8.927597e+03,0.0000,1.686601e+03,5.479471e+03,1.173047e+04,3.712257e+04
Gas Volume (scf/day),6925.0,6.978690e+06,7.100875e+06,0.0000,1.434288e+06,4.770461e+06,9.892230e+06,3.004494e+07
Water Production (stb/day),6925.0,1.148056e+04,1.148448e+04,-2879.8136,8.032330e+01,5.529413e+03,2.226151e+04,5.044416e+04

In [9]:
# Convert to datetime and create time-based features
dataset['PRODUCTION DATE'] = pd.to_datetime(dataset['PRODUCTION DATE'], format="%d/%m/%Y %H:%M")
val_data['PRODUCTION DATE'] = pd.to_datetime(val_data['PRODUCTION DATE'], format="%Y-%m-%d %H:%M:%S")

# Create time-based features
for df in [dataset,val_data]:
    df['Month'] = df['PRODUCTION DATE'].dt.month
    df['Year'] = df['PRODUCTION DATE'].dt.year
    df['DayOfYear'] = df['PRODUCTION DATE'].dt.dayofyear
    df['WeekOfYear'] = df['PRODUCTION DATE'].dt.isocalendar().week

In [10]:
val_data

,PRODUCTION DATE,Field Name,WELL_BORE_CODE,N_WELL_BORE_CODE,WellBore Name,FLOW_KIND,WELL_TYPE,Downhole Pressure (PSI),Downhole Temperature (Kelvin),Average Tubing Pressure,Annulus Pressure (PSI),AVG WHP (PSI),Choke Size,Oil Production (stb/day),Gas Volume (scf/day),Water Production (stb/day),Month,Year,DayOfYear,WeekOfYear
0,2015-07-01,DSEAT,DSEAT-001-F-1 C,105.0,001-F-1 C,production,OP,3061.253047,380.665745,2659.809580,0.0,401.443468,0.491632,NaN,NaN,NaN,7,2015,182,27
1,2015-07-02,DSEAT,DSEAT-001-F-1 C,105.0,001-F-1 C,production,OP,3247.951135,376.759980,2547.453670,0.0,700.497465,21.775180,NaN,NaN,NaN,7,2015,183,27
2,2015-07-03,DSEAT,DSEAT-001-F-1 C,105.0,001-F-1 C,production,OP,3333.012485,375.985300,2533.912265,0.0,799.100220,27.638780,NaN,NaN,NaN,7,2015,184,27
3,2015-07-04,DSEAT,DSEAT-001-F-1 C,105.0,001-F-1 C,production,OP,3404.022465,375.419010,2481.804485,0.0,922.217980,36.178940,NaN,NaN,NaN,7,2015,185,27
4,2015-07-05,DSEAT,DSEAT-001-F-1 C,105.0,001-F-1 C,production,OP,3465.473030,375.004710,2408.310945,0.0,1057.162085,45.424140,NaN,NaN,NaN,7,2015,186,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2070,2016-09-12,DSEAT,DSEAT-001-F-15 D,109.0,001-F-15 D,production,OP,5015.648165,363.184330,5015.648165,0.0,0.000000,13.876190,NaN,NaN,NaN,9,2016,256,37
2071,2016-09-13,DSEAT,DSEAT-001-F-15 D,109.0,001-F-15 D,production,OP,5015.648165,363.184330,5015.648165,0.0,0.000000,13.974080,NaN,NaN,NaN,9,2016,257,37
2072,2016-09-14,DSEAT,DSEAT-001-F-15 D,109.0,001-F-15 D,production,OP,5015.648165,363.184330,5015.648165,0.0,0.000000,14.063160,NaN,NaN,NaN,9,2016,258,37
2073,2016-09-15,DSEAT,DSEAT-001-F-15 D,109.0,001-F-15 D,production,OP,5015.648165,363.184330,5015.648165,0.0,0.000000,14.174450,NaN,NaN,NaN,9,2016,259,37
2074,2016-09-16,DSEAT,DSEAT-001-F-15 D,109.0,001-F-15 D,production,OP,5015.648165,363.184330,5015.648165,0.0,0.000000,14.232770,NaN,NaN,NaN,9,2016,260,37

In [11]:
# First, let's identify the columns with missing values
columns_with_missing = dataset.columns[dataset.isnull().any()].tolist()

for column in columns_with_missing:
    mean_value = dataset[column].mean()
    dataset[column].fillna(mean_value, inplace=True)

# Verify that all missing values have been filled
print(dataset.isnull().sum())

PRODUCTION DATE                  0
Field Name                       0
WELL_BORE_CODE                   0
N_WELL_BORE_CODE                 0
WellBore Name                    0
FLOW_KIND                        0
WELL_TYPE                        0
Downhole Pressure (PSI)          0
Downhole Temperature (Kelvin)    0
Average Tubing Pressure          0
Annulus Pressure (PSI)           0
AVG WHP (PSI)                    0
Choke Size                       0
Oil Production (stb/day)         0
Gas Volume (scf/day)             0
Water Production (stb/day)       0
Month                            0
Year                             0
DayOfYear                        0
WeekOfYear                       0
dtype: int64

In [12]:
val_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075 entries, 0 to 2074
Data columns (total 20 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   PRODUCTION DATE                2075 non-null   datetime64[ns]
 1   Field Name                     2075 non-null   object
 2   WELL_BORE_CODE                 2075 non-null   object
 3   N_WELL_BORE_CODE               2075 non-null   float64
 4   WellBore Name                  2075 non-null   object
 5   FLOW_KIND                      2075 non-null   object
 6   WELL_TYPE                      2075 non-null   object
 7   Downhole Pressure (PSI)        2075 non-null   float64
 8   Downhole Temperature (Kelvin)  2075 non-null   float64
 9   Average Tubing Pressure        2075 non-null   float64
 10  Annulus Pressure (PSI)         2075 non-null   float64
 11  AVG WHP (PSI)                  2075 non-null   float64
 12  Choke Size                     2075 non-null   float64
 13  Oil Production (stb/day)       0 non-null      float64
 14  Gas Volume (scf/day)           0 non-null      float64
 15  Water Production (stb/day)     0 non-null      float64
 16  Month                          2075 non-null   int32
 17  Year                           2075 non-null   int32
 18  DayOfYear                      2075 non-null   int32
 19  WeekOfYear                     2075 non-null   UInt32
dtypes: UInt32(1), datetime64[ns](1), float64(10), int32(3), object(5)
memory usage: 294.0+ KB

In [13]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline


# Define features and targets
numeric_features = ['N_WELL_BORE_CODE', 'Downhole Pressure (PSI)', 'Downhole Temperature (Kelvin)',
                    'Average Tubing Pressure', 'Annulus Pressure (PSI)', 'AVG WHP (PSI)',
                    'Choke Size', 'Month', 'Year', 'DayOfYear', 'WeekOfYear']


categorical_features = ['Field Name', 'WELL_BORE_CODE','WellBore Name', 'FLOW_KIND', 'WELL_TYPE']
targets = ['Oil Production (stb/day)', 'Gas Volume (scf/day)', 'Water Production (stb/day)']

X = dataset[numeric_features + categorical_features]
y = dataset[targets]

# Split data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create preprocessor
preprocessor = ColumnTransformer(
    transformers=[
        ('num', Pipeline([
            ('imputer', SimpleImputer(strategy='mean')),
            ('scaler', StandardScaler())
        ]), numeric_features),
        ('cat', Pipeline([
            ('imputer', SimpleImputer(strategy='most_frequent')),
            ('onehot', OneHotEncoder(handle_unknown='ignore'))
        ]), categorical_features)
    ])

# Prepare the full pipeline
full_pipeline = Pipeline([
    ('preprocessor', preprocessor)
])

# Fit and transform the data
X_train_processed = full_pipeline.fit_transform(X_train)
X_test_processed = full_pipeline.transform(X_test)

In [14]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.multioutput import MultiOutputRegressor

# Create and train the model
model = MultiOutputRegressor(RandomForestRegressor(n_estimators=100, random_state=42))

# Fit the pipeline and model
X_train_processed = full_pipeline.fit_transform(X_train)
model.fit(X_train_processed, y_train)

MultiOutputRegressor(estimator=RandomForestRegressor(random_state=42))

In [15]:
# model.predict(x_test)

In [16]:
# Process validation data
X_val_processed = full_pipeline.transform(val_data)

# Make predictions
val_predictions = model.predict(X_val_processed)
# val_predictions = model.predict(val_data)

# Add predictions to validation dataframe
val_data['Predicted Oil Production (stb/day)'] = val_predictions[:, 0]
val_data['Predicted Gas Volume (scf/day)'] = val_predictions[:, 1]
val_data['Predicted Water Production (stb/day)'] = val_predictions[:, 2]

In [17]:
from sklearn.model_selection import cross_val_score

# Perform cross-validation
cv_scores = cross_val_score(model, X_train_processed, y_train, cv=5, scoring='r2')
print(f"Cross-validation R2 scores: {cv_scores}")
print(f"Mean R2 score: {cv_scores.mean()}")

Cross-validation R2 scores: [0.94772514 0.96199449 0.96219688 0.96223314 0.94699415]
Mean R2 score: 0.9562287597186059

In [18]:
# Select required columns for submission
submission_df = val_data[['PRODUCTION DATE', 'WELL_BORE_CODE',
                        'Predicted Oil Production (stb/day)',
                        'Predicted Gas Volume (scf/day)',
                        'Predicted Water Production (stb/day)']]

# Save the submission file
submission_df.to_csv('Raymond_Boateng_2024_DSEAT_Datathon_SPE 5639082.csv', index=False)